spring.application.name=sentio.api
app.base-url=http://localhost:8080
spring.profiles.active=local

server.port=8080
# Timezone e formato de data
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.time-zone=America/Sao_Paulo
spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
spring.mvc.locale=UTF-8
spring.mvc.locale-resolver=fixed